variable "audience" { }
variable "aws_region_id" { }
variable "aws_caller_identity_account_id" { }
variable "identity_pool_id" { }
variable "identity_provider_name" { }
variable "issuer" { }
variable "jwks" { }
variable "task_change_flag" { }
variable "todos_create_arn" { }
